name: Run tests and generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Run jar
        run: java -jar ./artifacts/aqa-shop.jar

      - name: Set executable permissions for gradlew
        run: chmod +x gradlew
    
      
      - name: Run tests
        run: ./gradlew clean test
      
      - name: Generate Allure Report
        run: ./gradlew allureReport
      
      - name: Serve Allure Report
        run: ./gradlew allureServe
