name: Run tests and publish report
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run tests
        run: java -jar ./artifacts/aqa-shop.jar

      - name: Set executable permissions for gradlew
        run: chmod +x gradlew

      - name: Load test report history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: main
          repository: https://github.com/OAOblat/course_project
          path: report

      - name: Build test report
        uses: allure-framework/allure-github-action@v1
        if: always()

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report/allure-report
